-- MySQL Script generated by MySQL Workbench
-- 08/21/14 18:27:10
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema UniversitySystem
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `UniversitySystem` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `UniversitySystem` ;

-- -----------------------------------------------------
-- Table `UniversitySystem`.`Faculties`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `UniversitySystem`.`Faculties` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UniversitySystem`.`Deparments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `UniversitySystem`.`Deparments` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NULL,
  `FacultyID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `FK_Departments_Faculties_idx` (`FacultyID` ASC),
  CONSTRAINT `FK_Departments_Faculties`
    FOREIGN KEY (`FacultyID`)
    REFERENCES `UniversitySystem`.`Faculties` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UniversitySystem`.`Professors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `UniversitySystem`.`Professors` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `DeparmentID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `FK_Professors_Deparments_idx` (`DeparmentID` ASC),
  CONSTRAINT `FK_Professors_Deparments`
    FOREIGN KEY (`DeparmentID`)
    REFERENCES `UniversitySystem`.`Deparments` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UniversitySystem`.`Titles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `UniversitySystem`.`Titles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UniversitySystem`.`ProfessorsTitles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `UniversitySystem`.`ProfessorsTitles` (
  `ProfessorID` INT NOT NULL,
  `TitleID` INT NOT NULL,
  INDEX `FK_ProfessorsTitles_Professors_idx` (`ProfessorID` ASC),
  INDEX `FK_ProfessorsTitles_Titles_idx` (`TitleID` ASC),
  CONSTRAINT `FK_ProfessorsTitles_Professors`
    FOREIGN KEY (`ProfessorID`)
    REFERENCES `UniversitySystem`.`Professors` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_ProfessorsTitles_Titles`
    FOREIGN KEY (`TitleID`)
    REFERENCES `UniversitySystem`.`Titles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UniversitySystem`.`Courses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `UniversitySystem`.`Courses` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `DeparmentID` INT NOT NULL,
  `ProfessorID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `FK_Courses_Deparments_idx` (`DeparmentID` ASC),
  INDEX `FK_Courses_Professors_idx` (`ProfessorID` ASC),
  CONSTRAINT `FK_Courses_Deparments`
    FOREIGN KEY (`DeparmentID`)
    REFERENCES `UniversitySystem`.`Deparments` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_Courses_Professors`
    FOREIGN KEY (`ProfessorID`)
    REFERENCES `UniversitySystem`.`Professors` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UniversitySystem`.`table1`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `UniversitySystem`.`table1` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UniversitySystem`.`Students`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `UniversitySystem`.`Students` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `FacultyID` INT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `FK_Students_Faculties_idx` (`FacultyID` ASC),
  CONSTRAINT `FK_Students_Faculties`
    FOREIGN KEY (`FacultyID`)
    REFERENCES `UniversitySystem`.`Faculties` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `UniversitySystem`.`StudentsCourses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `UniversitySystem`.`StudentsCourses` (
  `StudentID` INT NOT NULL,
  `CourseID` INT NOT NULL,
  INDEX `FK_StudentsCourses_Students_idx` (`StudentID` ASC),
  INDEX `FK_StudentsCourses_Courses_idx` (`CourseID` ASC),
  CONSTRAINT `FK_StudentsCourses_Students`
    FOREIGN KEY (`StudentID`)
    REFERENCES `UniversitySystem`.`Students` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_StudentsCourses_Courses`
    FOREIGN KEY (`CourseID`)
    REFERENCES `UniversitySystem`.`Courses` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
